// automatically generated by the FlatBuffers compiler, do not modify

package org.deep_thinker.model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GetFirstActionResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static GetFirstActionResponse getRootAsGetFirstActionResponse(ByteBuffer _bb) { return getRootAsGetFirstActionResponse(_bb, new GetFirstActionResponse()); }
  public static GetFirstActionResponse getRootAsGetFirstActionResponse(ByteBuffer _bb, GetFirstActionResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetFirstActionResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int action() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createGetFirstActionResponse(FlatBufferBuilder builder,
      int action) {
    builder.startTable(1);
    GetFirstActionResponse.addAction(builder, action);
    return GetFirstActionResponse.endGetFirstActionResponse(builder);
  }

  public static void startGetFirstActionResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addAction(FlatBufferBuilder builder, int action) { builder.addInt(0, action, 0); }
  public static int endGetFirstActionResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GetFirstActionResponse get(int j) { return get(new GetFirstActionResponse(), j); }
    public GetFirstActionResponse get(GetFirstActionResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

